name: Deploy using commit ID

on:
  workflow_dispatch:
    inputs:
      GitSHA:
        description: "Provide GitHub Commit ID"
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GitSHA: ${{ inputs.GitSHA }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GitSHA }}  # Uses the commit ID input

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Echo World
        run: echo "Hello World!"

      - name: Print Commit ID
        run: echo "Commit ID is $GitSHA"
